### ISSUE TITLE
Prijzen aanpassen

### ISSUE THREAD

**Issue by yvonnebierens** [hans2103/schoonheidEersel#2]
Per 1 januari 2017 gelden nieuwe prijzen. 
Deze moeten einde dit jaar op de site gepubliceerd worden. 

stappenplan

- [x] prijzen wijzigen in https://github.com/hans2103/schoonheidEersel/blob/master/app/_data/treatments.yml (@yvonnebierens)
- [x] issue toewijzen aan Hans via assignees
- [x] wijzigingen live zetten op 31-12-2016 (@hans2103)

**Comment by hans2103** [comment]
done
