### ISSUE TITLE
foutjes onder verven

### ISSUE THREAD

**Issue by hans2103** [hans2103/schoonheidEersel#8]
Ontvangen via de mail:

> Verder staan er onder het kopje 'verven' wat foutjes"

**Comment by hans2103** [comment]
@yvonnebierens je kunt beter aangeven wat je ziet en wat het moet zijn. Ik zie niet alles als een fout wat  jij wel als fout ziet. En omgekeerd.

**Comment by yvonnebierens** [comment]
Oké

Op wo 11 dec. 2019 15:24 schreef Hans Kuijpers <notifications@github.com>:
